<?php

namespace colpatria\folmularioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * municipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class municipioRepository extends EntityRepository
{
}
